### ISSUE TITLE
Try using .forEach when working with arrays

### ISSUE THREAD

**Issue by Razpudding** [Aidan98/web-app-from-scratch-1920#1]
Good job getting the fetch to work!

[You could try using .forEach here instead of a handmade forloop](https://github.com/Aidan98/web-app-from-scratch-1920/blob/master/docs/js/app.js#L33) as it's less error prone.

**Comment by CountNick** [comment]
[Tried to write an example](https://github.com/Aidan98/web-app-from-scratch-1920/issues/6)

**Comment by Aidan98** [comment]
I used Nick's example to write my foreach.
