### ISSUE TITLE
A forEach function could be easier for an array

### ISSUE THREAD

**Issue by kylebot0** [Aidan98/web-app-from-scratch-1920#3]
https://github.com/Aidan98/web-app-from-scratch-1920/blob/bc94ae175704d2d7c9f53022fd201ad5b9dea00e/docs/js/app.js#L1-L4

Try using a forEach on the array of data, you can loop through it more easily.

**Comment by joostf** [comment]
Why is a foreEach easier, @kylebot0 ?

**Comment by Aidan98** [comment]
Fixed
