### ISSUE TITLE
innerHTML

### ISSUE THREAD

**Issue by CountNick** [Aidan98/web-app-from-scratch-1920#6]
https://github.com/Aidan98/web-app-from-scratch-1920/blob/bc94ae175704d2d7c9f53022fd201ad5b9dea00e/docs/js/app.js#L33-L38

you can also insertAdjecentHTML:

```js
    data.results  
    .forEach(element => {       
        let li = document.createElement('li')

        li
        .insertAdjacentHTML('afterbegin',  <p>${element.federation.name}</p>`)

        main.appendChild(section)

    });
```
Don't know if the above code will work instantly.. 

a nice resource:

[resource](https://www.myhowtoonline.com/how-to-create-an-h1-element-with-javascript/)

**Comment by Aidan98** [comment]
Thank you for the suggestion, I've implemented the code you've provided into  my own code.
